language:      node_js
node_js:
  - '10'
  - '11'
  - stable
cache:
  directories:
  - client/node_modules
  - server/node_modules
script:
  - cd client && npm install && npm run build && npm test
after_script:  cd client && npm run coveralls
