projects:
  server:
    schemaPath:  "./src/schema.graphql"
    extensions:
      endpoints:
        default: "${env:HOST}${env:PORT}"
  prisma:
    schemaPath:  "src/generated/prisma.graphql"
    extensions:
      prisma:    prisma.yml
